# BerkeleyDB
PKG_VER=3.46.0
PKG_URL="https://github.com/sqlite/sqlite/archive/refs/tags/version-${PKG_VER}.tar.gz"
PKG_DEPS="lfs/libedit"
BUILD_PROCESS=configmake
PKG_AUTOCONF=1
CONF_FLAGS="--enable-fts5"
PKG_CPPFLAGS="-DSQLITE_ENABLE_FTS3=1"
PKG_CPPFLAGS+=" -DSQLITE_ENABLE_FTS4=1"
PKG_CPPFLAGS+=" -DSQLITE_ENABLE_COLUMN_METADATA=1"
PKG_CPPFLAGS+=" -DSQLITE_ENABLE_UNLOCK_NOTIFY=1"
PKG_CPPFLAGS+=" -DSQLITE_ENABLE_DBSTAT_VTAB=1"
PKG_CPPFLAGS+=" -DSQLITE_SECURE_DELETE=1"
PKG_CPPFLAGS+=" -DSQLITE_ENABLE_FTS3_TOKENIZER=1"
PKG_MAKETARGETS=",install"
