# shellcheck shell=bash
# shellcheck disable=SC2154
# hostapd: pre-build script, sourced by runprebuild.sh (cwd: ${PKG_SRCPATH}, set -x, no -e).
# Every ALL_CAPS variable visible to package.env is available here as ${VAR}.

cat > hostapd/.config <<-EOF
	CONFIG_DRIVER_HOSTAP=y
	CONFIG_DRIVER_WIRED=y
	CONFIG_DRIVER_NL80211=y
	CONFIG_LIBNL32=y
	CONFIG_DRIVER_NONE=y
	CONFIG_IAPP=y
	CONFIG_RSN_PREAUTH=y
	CONFIG_IEEE80211W=y
	CONFIG_EAP=y
	CONFIG_ERP=y
	CONFIG_EAP_MD5=y
	CONFIG_EAP_TLS=y
	CONFIG_EAP_MSCHAPV2=y
	CONFIG_EAP_PEAP=y
	CONFIG_EAP_GTC=y
	CONFIG_EAP_TTLS=y
	CONFIG_EAP_SIM=y
	CONFIG_EAP_AKA=y
	CONFIG_EAP_AKA_PRIME=y
	CONFIG_EAP_PAX=y
	CONFIG_EAP_PSK=y
	CONFIG_EAP_PWD=y
	CONFIG_EAP_SAKE=y
	CONFIG_EAP_GPSK=y
	CONFIG_EAP_GPSK_SHA256=y
	CONFIG_EAP_FAST=y
	CONFIG_WPS=y
	CONFIG_WPS_UPNP=y
	CONFIG_WPS_NFC=y
	CONFIG_EAP_IKEV2=y
	CONFIG_EAP_TNC=y
	CONFIG_EAP_EKE=y
	CONFIG_PKCS12=y
	CONFIG_RADIUS_SERVER=y
	CONFIG_IPV6=y
	CONFIG_IEEE80211R=y
	CONFIG_IEEE80211N=y
	CONFIG_WNM=y
	CONFIG_IEEE80211AC=y
	CONFIG_DEBUG_FILE=y
	CONFIG_DEBUG_LINUX_TRACING=y
	CONFIG_FULL_DYNAMIC_VLAN=y
	CONFIG_VLAN_NETLINK=y
EOF
